apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: default
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: "5.7.21"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
######### Deny Admission if image uses latest tag ################
        image: paulbouwer/hello-kubernetes:latest #1.5
        ports:
        - containerPort: 8080
