apiVersion: v1
kind: Pod
metadata:
  name: containers-resource-constraints-required-test
spec:
  containers:
  - name: hello
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    securityContext:
      privileged: true
      runAsNonRoot: true
    resources:
      limits:
        cpu: "300m"
        memory: "4000Mi"
  hostNetwork: true
