apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NamespaceDenyInstioInjection
metadata:
  name: namespacedenyinstioinjection
spec:
  match:
    kinds:
    - apiGroups:
      - '""'
      kinds:
      - Namespace
